name: Progress Automation

on:
  push:
    paths:
      - 'docs/progress/**'
      - 'scripts/progress/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'docs/progress/**'
      - 'scripts/progress/**'
      - 'requirements.txt'
  workflow_dispatch: {}

jobs:
  progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Update progress metrics
        run: python scripts/progress/update_progress.py --write --summary
      - name: Show diff
        run: |
          git diff --name-only || true
      - name: Upload updated metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: progress-metrics
          path: docs/progress/metrics.json
      - name: Commit changes (non-main branches only)
        if: github.ref != 'refs/heads/main'
        run: |
          if ! git diff --quiet; then
            git config user.name 'progress-bot'
            git config user.email 'progress-bot@users.noreply.github.com'
            git add docs/progress/metrics.json
            git commit -m 'chore(progress): auto-update metrics'
            git push || true
          fi
      - name: Job Summary
        run: |
          echo '### Progress Summary' >> $GITHUB_STEP_SUMMARY
          python scripts/progress/update_progress.py --json >> $GITHUB_STEP_SUMMARY
